# Generated by Django 3.1.3 on 2020-11-04 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='capstone',
            old_name='movieGenre',
            new_name='mgenre',
        ),
        migrations.RenameField(
            model_name='capstone',
            old_name='movieName',
            new_name='mname',
        ),
        migrations.RenameField(
            model_name='capstone',
            old_name='moviewReview',
            new_name='mreview',
        ),
    ]
