# Generated by Django 3.1.3 on 2020-11-21 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_calculate'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvgScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mname', models.CharField(max_length=100)),
                ('mgenre', models.CharField(max_length=200)),
                ('mscore', models.FloatField()),
            ],
        ),
    ]
